# Generated by Django 4.0.2 on 2022-03-01 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryAddressStructure',
            fields=[
                ('country_id', models.IntegerField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=100)),
                ('country_iso', models.CharField(max_length=100)),
                ('address_format', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('address_id', models.IntegerField(primary_key=True, serialize=False)),
                ('addressLine', models.JSONField()),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.countryaddressstructure')),
            ],
        ),
    ]
