# Generated by Django 4.0.2 on 2022-03-08 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryAddressStructure',
            fields=[
                ('country_id', models.IntegerField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=100)),
                ('country_iso', models.CharField(max_length=100)),
                ('address_format', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'myapi_countryaddressstructure',
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('state_id', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=100)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_countryID', to='myapi.countryaddressstructure')),
            ],
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('address_id', models.IntegerField(primary_key=True, serialize=False)),
                ('addressLine', models.JSONField()),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_countryID', to='myapi.countryaddressstructure')),
            ],
        ),
    ]
